const ActionTypes = {
    SET_BALANCE: "SET_BALANCE",
    ADD_OPERATION: "ADD_OPERATION",
    DELETE_OPERATION: "DELETE_OPERATION",
    UPDATE_BALANCE_AFTER_DELETE: "UPDATE_BALANCE_AFTER_DELETE",
    ADD_CATEGORY: "ADD_CATEGORY",
    DELETE_CATEGORY: "DELETE_CATEGORY",
    CHANGE_THEME: "CHANGE_THEME",
    DELETE_SUGGESTION: "DELETE_SUGGESTION"
};

export default ActionTypes;